name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: access1005719582.webspace-data.io
          username: u116384827
          password: ${{ secrets.ftp_password }}
          port: 22
          source: "./"  # Adjust this to the directory/files to upload
          target: "/htdocs/"  # Replace with the correct web root folder
