on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: access1005719582.webspace-data.io
        username: u116384827
        password: Shakil1234567890
        local-dir: ./  # Adjust this to match your repository structure
        server-dir: /  # Adjust this if your web root is in a subdirectory
